#!/usr/bin/env bash
set -euo pipefail

# Run criterion benchmarks, append results to a CSV history file,
# and regenerate BENCHMARKS.md with the latest run.
#
# Usage:
#   ./scripts/bench-history.sh              # defaults to bench-history.csv
#   ./scripts/bench-history.sh results.csv  # custom output file

HISTORY_FILE="${1:-bench-history.csv}"
BENCHMARKS_MD="BENCHMARKS.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Create header if file doesn't exist
if [ ! -f "$HISTORY_FILE" ]; then
    echo "timestamp,commit,branch,benchmark,estimate_ns" > "$HISTORY_FILE"
fi

echo "┌─────────────────────────────────────────────┐"
echo "│  yantra benchmark suite                     │"
echo "├─────────────────────────────────────────────┤"
echo "│  commit : $COMMIT                              │"
echo "│  branch : $BRANCH                              │"
echo "│  date   : $TIMESTAMP   │"
echo "└─────────────────────────────────────────────┘"
echo ""

# Run benchmarks and capture output, stripping ANSI escape codes
BENCH_OUTPUT=$(cargo bench --bench yantra_bench 2>&1 | sed 's/\x1b\[[0-9;]*m//g')

# Parse criterion output into arrays
declare -a BENCH_NAMES=()
declare -a BENCH_NS=()
declare -a BENCH_DISPLAY=()

PREV_LINE=""
while IFS= read -r line; do
    if [[ "$line" == *"time:"*"["* ]]; then
        BENCH_NAME=$(echo "$line" | sed -E 's/[[:space:]]*time:.*//' | xargs)
        if [ -z "$BENCH_NAME" ]; then
            BENCH_NAME=$(echo "$PREV_LINE" | xargs)
        fi

        VALS=$(echo "$line" | sed -E 's/.*\[(.+)\]/\1/')
        MEDIAN=$(echo "$VALS" | awk '{print $3}')
        UNIT=$(echo "$VALS" | awk '{print $4}')

        # Normalize to nanoseconds
        case "$UNIT" in
            ps)  NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 / 1000}') ;;
            ns)  NS="$MEDIAN" ;;
            µs|us)  NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 * 1000}') ;;
            ms)  NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 * 1000000}') ;;
            s)   NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 * 1000000000}') ;;
            *)   NS="$MEDIAN" ;;
        esac

        # Human-friendly display value
        DISPLAY="${MEDIAN} ${UNIT}"

        BENCH_NAMES+=("$BENCH_NAME")
        BENCH_NS+=("$NS")
        BENCH_DISPLAY+=("$DISPLAY")

        echo "${TIMESTAMP},${COMMIT},${BRANCH},${BENCH_NAME},${NS}" >> "$HISTORY_FILE"
    fi
    PREV_LINE="$line"
done <<< "$BENCH_OUTPUT"

TOTAL=${#BENCH_NAMES[@]}

# ── Print summary table ──────────────────────────────────────────────────

echo ""
echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  Results                                                     │"
echo "├────────────────────────────────────────────┬─────────────────┤"
printf "│ %-42s │ %15s │\n" "Benchmark" "Time"
echo "├────────────────────────────────────────────┼─────────────────┤"

CURRENT_GROUP=""
for i in $(seq 0 $((TOTAL - 1))); do
    NAME="${BENCH_NAMES[$i]}"
    DISPLAY="${BENCH_DISPLAY[$i]}"
    GROUP="${NAME%%/*}"

    if [ "$GROUP" != "$CURRENT_GROUP" ]; then
        if [ -n "$CURRENT_GROUP" ]; then
            echo "├────────────────────────────────────────────┼─────────────────┤"
        fi
        CURRENT_GROUP="$GROUP"
    fi

    printf "│ %-42s │ %15s │\n" "$NAME" "$DISPLAY"
done

echo "└────────────────────────────────────────────┴─────────────────┘"
echo ""
echo "Appended ${TOTAL} entries to ${HISTORY_FILE}"

# ── Generate BENCHMARKS.md ───────────────────────────────────────────────

# Check for previous run to compute deltas
PREV_COMMIT=""
if [ -f "$HISTORY_FILE" ]; then
    # Get the second-most-recent commit (skip current run)
    PREV_COMMIT=$(awk -F, 'NR>1 && $2 != "'"$COMMIT"'" {print $2}' "$HISTORY_FILE" | tail -1)
fi

{
    echo "# Benchmarks"
    echo ""
    echo "> Auto-generated by \`scripts/bench-history.sh\` — do not edit manually."
    echo ""
    echo "| Field | Value |"
    echo "|-------|-------|"
    echo "| Date | \`${TIMESTAMP}\` |"
    echo "| Commit | \`${COMMIT}\` |"
    echo "| Branch | \`${BRANCH}\` |"
    echo "| Toolchain | \`$(rustc --version 2>/dev/null || echo unknown)\` |"
    echo ""
    echo "## Results"
    echo ""

    CURRENT_GROUP=""
    for i in $(seq 0 $((TOTAL - 1))); do
        NAME="${BENCH_NAMES[$i]}"
        NS="${BENCH_NS[$i]}"
        DISPLAY="${BENCH_DISPLAY[$i]}"
        GROUP="${NAME%%/*}"
        BENCH="${NAME#*/}"

        if [ "$GROUP" != "$CURRENT_GROUP" ]; then
            if [ -n "$CURRENT_GROUP" ]; then
                echo ""
            fi
            echo "### ${GROUP}"
            echo ""
            echo "| Benchmark | Time | ns |"
            echo "|-----------|------|----|"
            CURRENT_GROUP="$GROUP"
        fi

        # Look up previous value for delta
        DELTA=""
        if [ -n "$PREV_COMMIT" ]; then
            PREV_NS=$(awk -F, '$2 == "'"$PREV_COMMIT"'" && $4 == "'"$NAME"'" {print $5}' "$HISTORY_FILE" | tail -1)
            if [ -n "$PREV_NS" ]; then
                PCT=$(awk "BEGIN {d=($NS - $PREV_NS) / $PREV_NS * 100; printf \"%+.1f%%\", d}")
                DELTA=" ($PCT)"
            fi
        fi

        echo "| ${BENCH} | ${DISPLAY} | ${NS}${DELTA} |"
    done

    echo ""
    echo "---"
    echo ""
    echo "Run benchmarks: \`./scripts/bench-history.sh\`"
    echo ""
    echo "History: [\`bench-history.csv\`](bench-history.csv)"
} > "$BENCHMARKS_MD"

echo "Updated ${BENCHMARKS_MD}"
