#!/usr/bin/env bash
set -euo pipefail

# Run Cyrius benchmarks, append results to a CSV history file,
# and regenerate BENCHMARKS.md with the latest 3 runs for trend tracking.
#
# Usage:
#   ./scripts/bench-history.sh              # defaults to bench-history.csv
#   ./scripts/bench-history.sh results.csv  # custom output file

HISTORY_FILE="${1:-bench-history.csv}"
BENCHMARKS_MD="BENCHMARKS.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
CC="${CC:-$(command -v cyrius 2>/dev/null || echo "$HOME/Repos/cyrius/build/cc3")}"

# Create header if file doesn't exist
if [ ! -f "$HISTORY_FILE" ]; then
    echo "timestamp,commit,branch,benchmark,estimate_ns" > "$HISTORY_FILE"
fi

echo "┌─────────────────────────────────────────────┐"
echo "│  yukti benchmark suite (cyrius)             │"
echo "├─────────────────────────────────────────────┤"
echo "│  commit : $COMMIT                              │"
echo "│  branch : $BRANCH                              │"
echo "│  date   : $TIMESTAMP   │"
echo "└─────────────────────────────────────────────┘"
echo ""

# Build benchmarks
echo "Building benchmarks..."
mkdir -p build
cat benches/bench.bcyr | "$CC" > build/yukti_bench 2>/dev/null
chmod +x build/yukti_bench

# Run benchmarks and capture output
echo "Running benchmarks..."
BENCH_OUTPUT=$(./build/yukti_bench 2>/dev/null)

# Parse bench output — format: "benchmark_name: Xns (N iterations)"
declare -a BENCH_NAMES=()
declare -a BENCH_NS=()
declare -a BENCH_DISPLAY=()

while IFS= read -r line; do
    # Match lines like: "device_id/create: 42ns (100000 iterations)"
    if [[ "$line" =~ ^[[:space:]]*([a-zA-Z_/]+):[[:space:]]*([0-9]+)ns ]]; then
        NAME="${BASH_REMATCH[1]}"
        NS="${BASH_REMATCH[2]}"
        BENCH_NAMES+=("$NAME")
        BENCH_NS+=("$NS")
        BENCH_DISPLAY+=("${NS} ns")
        echo "${TIMESTAMP},${COMMIT},${BRANCH},${NAME},${NS}" >> "$HISTORY_FILE"
    fi
done <<< "$BENCH_OUTPUT"

TOTAL=${#BENCH_NAMES[@]}

if [ "$TOTAL" -eq 0 ]; then
    echo "No benchmark results parsed. Raw output:"
    echo "$BENCH_OUTPUT"
    exit 1
fi

# ── Print summary table ──────────────────────────────────────────────────

echo ""
echo "┌──────────────────────────────────────────────────────────────┐"
echo "│  Results                                                     │"
echo "├────────────────────────────────────────────┬─────────────────┤"
printf "│ %-42s │ %15s │\n" "Benchmark" "Time"
echo "├────────────────────────────────────────────┼─────────────────┤"

CURRENT_GROUP=""
for i in $(seq 0 $((TOTAL - 1))); do
    NAME="${BENCH_NAMES[$i]}"
    DISPLAY="${BENCH_DISPLAY[$i]}"
    GROUP="${NAME%%/*}"

    if [ "$GROUP" != "$CURRENT_GROUP" ]; then
        if [ -n "$CURRENT_GROUP" ]; then
            echo "├────────────────────────────────────────────┼─────────────────┤"
        fi
        CURRENT_GROUP="$GROUP"
    fi

    printf "│ %-42s │ %15s │\n" "$NAME" "$DISPLAY"
done

echo "└────────────────────────────────────────────┴─────────────────┘"
echo ""
echo "Appended ${TOTAL} entries to ${HISTORY_FILE}"

# ── Generate BENCHMARKS.md ────────────────────────────────────────────

mapfile -t RUNS < <(awk -F, 'NR>1 {print $1","$2}' "$HISTORY_FILE" | sort -u | tail -3)
NUM_RUNS=${#RUNS[@]}

declare -a RUN_TS=()
declare -a RUN_COMMIT=()
for run in "${RUNS[@]}"; do
    RUN_TS+=("${run%%,*}")
    RUN_COMMIT+=("${run#*,}")
done

lookup_ns() {
    local commit="$1" bench="$2"
    awk -F, -v c="$commit" -v b="$bench" '$2 == c && $4 == b {print $5}' "$HISTORY_FILE" | tail -1
}

format_ns() {
    local ns="$1"
    if [ -z "$ns" ]; then echo "—"; return; fi
    awk "BEGIN {
        v = $ns
        if (v < 1)             printf \"%.2f ps\", v * 1000
        else if (v < 1000)     printf \"%.2f ns\", v
        else if (v < 1000000)  printf \"%.2f µs\", v / 1000
        else                    printf \"%.2f ms\", v / 1000000
    }"
}

{
    echo "# Benchmarks"
    echo ""
    echo "> Auto-generated by \`scripts/bench-history.sh\` — do not edit manually."
    echo ""
    echo "## Run History"
    echo ""
    echo "| | $(for i in $(seq 0 $((NUM_RUNS - 1))); do printf "Run %d | " "$((i + 1))"; done)"
    echo "|---|$(for _ in $(seq 1 "$NUM_RUNS"); do printf -- "---|"; done)"
    echo "| **Date** | $(for i in $(seq 0 $((NUM_RUNS - 1))); do printf "\`%s\` | " "${RUN_TS[$i]}"; done)"
    echo "| **Commit** | $(for i in $(seq 0 $((NUM_RUNS - 1))); do printf "\`%s\` | " "${RUN_COMMIT[$i]}"; done)"
    echo "| **Toolchain** | $(for _ in $(seq 1 "$NUM_RUNS"); do printf "\`cyrius\` | "; done)"
    echo ""
    echo "## Results"
    echo ""

    CURRENT_GROUP=""
    for i in $(seq 0 $((TOTAL - 1))); do
        NAME="${BENCH_NAMES[$i]}"
        GROUP="${NAME%%/*}"
        BENCH="${NAME#*/}"

        if [ "$GROUP" != "$CURRENT_GROUP" ]; then
            if [ -n "$CURRENT_GROUP" ]; then echo ""; fi
            echo "### ${GROUP}"
            echo ""
            printf "| Benchmark |"
            for r in $(seq 0 $((NUM_RUNS - 1))); do printf " \`%s\` |" "${RUN_COMMIT[$r]}"; done
            echo " Δ first→last |"
            printf "|-----------|"
            for _ in $(seq 1 "$NUM_RUNS"); do printf -- "------|"; done
            echo "------|"
            CURRENT_GROUP="$GROUP"
        fi

        printf "| %s |" "$BENCH"
        FIRST_NS=""
        LAST_NS=""
        for r in $(seq 0 $((NUM_RUNS - 1))); do
            VAL=$(lookup_ns "${RUN_COMMIT[$r]}" "$NAME")
            FORMATTED=$(format_ns "$VAL")
            printf " %s |" "$FORMATTED"
            if [ -n "$VAL" ]; then
                [ -z "$FIRST_NS" ] && FIRST_NS="$VAL"
                LAST_NS="$VAL"
            fi
        done
        if [ -n "$FIRST_NS" ] && [ -n "$LAST_NS" ] && [ "$FIRST_NS" != "$LAST_NS" ]; then
            DELTA=$(awk "BEGIN {d=($LAST_NS - $FIRST_NS) / $FIRST_NS * 100; printf \"%+.1f%%\", d}")
        else
            DELTA="—"
        fi
        printf " %s |" "$DELTA"
        echo ""
    done

    echo ""
    echo "---"
    echo ""
    echo "Run benchmarks: \`./scripts/bench-history.sh\`"
    echo ""
    echo "History: [\`bench-history.csv\`](bench-history.csv)"
} > "$BENCHMARKS_MD"

echo "Updated ${BENCHMARKS_MD}"
